extern void void robot_world_distances_init(      double *u4,
                                                  double *u5,
                                                  double *u6,
                                                  double *u7,
                                                  double *u8,
                                                  double *u9,
                                                  double *u10,
                                                  double *u11,
                                                  double *u12,
                                                  double *u13,
                                                  double *u14,
                                                  double *u15,
                                                  double *u16,
                                                  double *u17,
                                                  double *y7,
                                                  double *y8,
                                                  int  *work1,
                                                  void *work2,
                                                  void *work3,
                                                  void *work4);

extern void robot_world_distances_terminate(void *work2,
                                      void *work3,
                                      void *work4);